ALTER TABLE users
    ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'USER';

ALTER TABLE users
    ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE users
    ADD COLUMN account_non_expired BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE users
    ADD COLUMN account_non_locked BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE users
    ADD COLUMN credentials_non_expired BOOLEAN NOT NULL DEFAULT TRUE;